


SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";






CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";






CREATE TYPE "public"."media_type" AS ENUM (
    'movie',
    'series'
);


ALTER TYPE "public"."media_type" OWNER TO "postgres";


CREATE TYPE "public"."status" AS ENUM (
    'watched',
    'to_watch'
);


ALTER TYPE "public"."status" OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."media" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "tmdb_id" numeric NOT NULL,
    "title" "text" NOT NULL,
    "poster_path" "text",
    "release_date" "text",
    "director" "text",
    "media_type" "public"."media_type" DEFAULT 'movie'::"public"."media_type" NOT NULL,
    "last_air_date" "text"
);


ALTER TABLE "public"."media" OWNER TO "postgres";


ALTER TABLE "public"."media" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."movies_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."user_media" (
    "id" bigint NOT NULL,
    "user_id" "uuid" DEFAULT "auth"."uid"() NOT NULL,
    "media_id" bigint NOT NULL,
    "watchStatus" "public"."status" NOT NULL,
    "added_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "watched_date" timestamp with time zone,
    "rating" numeric,
    "review" "text"
);


ALTER TABLE "public"."user_media" OWNER TO "postgres";


ALTER TABLE "public"."user_media" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."user_movies_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE ONLY "public"."media"
    ADD CONSTRAINT "media_tmdb_id_media_type_key" UNIQUE ("tmdb_id", "media_type");



ALTER TABLE ONLY "public"."media"
    ADD CONSTRAINT "movies_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."media"
    ADD CONSTRAINT "movies_tmdb_id_key" UNIQUE ("tmdb_id");



ALTER TABLE ONLY "public"."user_media"
    ADD CONSTRAINT "user_media_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."user_media"
    ADD CONSTRAINT "user_movies_id_key" UNIQUE ("id");



ALTER TABLE ONLY "public"."user_media"
    ADD CONSTRAINT "user_movies_movie_id_fkey" FOREIGN KEY ("media_id") REFERENCES "public"."media"("id");



CREATE POLICY "Enable insert for authenticated users only" ON "public"."media" FOR INSERT TO "authenticated" WITH CHECK (true);



CREATE POLICY "Enable insert for authenticated users only" ON "public"."user_media" FOR INSERT TO "authenticated" WITH CHECK ((( SELECT "auth"."uid"() AS "uid") = "user_id"));



CREATE POLICY "Enable read access for authenticated users only" ON "public"."media" FOR SELECT TO "authenticated" USING (true);



CREATE POLICY "Enable update by authenticated users only" ON "public"."media" FOR UPDATE USING (true) WITH CHECK (true);



CREATE POLICY "Enable users to delete their own data only" ON "public"."user_media" FOR DELETE USING ((( SELECT "auth"."uid"() AS "uid") = "user_id"));



CREATE POLICY "Enable users to update their own data only" ON "public"."user_media" FOR UPDATE USING ((( SELECT "auth"."uid"() AS "uid") = "user_id")) WITH CHECK ((( SELECT "auth"."uid"() AS "uid") = "user_id"));



CREATE POLICY "Enable users to view their own data only" ON "public"."user_media" FOR SELECT TO "authenticated" USING ((( SELECT "auth"."uid"() AS "uid") = "user_id"));



ALTER TABLE "public"."media" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."user_media" ENABLE ROW LEVEL SECURITY;




ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";


GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";








































































































































































GRANT ALL ON TABLE "public"."media" TO "anon";
GRANT ALL ON TABLE "public"."media" TO "authenticated";
GRANT ALL ON TABLE "public"."media" TO "service_role";



GRANT ALL ON SEQUENCE "public"."movies_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."movies_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."movies_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."user_media" TO "anon";
GRANT ALL ON TABLE "public"."user_media" TO "authenticated";
GRANT ALL ON TABLE "public"."user_media" TO "service_role";



GRANT ALL ON SEQUENCE "public"."user_movies_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."user_movies_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."user_movies_id_seq" TO "service_role";









ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";































drop extension if exists "pg_net";


  create policy "Give users access to own folder 1bs1gex_0"
  on "storage"."objects"
  as permissive
  for delete
  to public
using (((bucket_id = 'avatar'::text) AND (( SELECT (auth.uid())::text AS uid) = (storage.foldername(name))[1])));



  create policy "Give users access to own folder 1bs1gex_1"
  on "storage"."objects"
  as permissive
  for select
  to public
using (((bucket_id = 'avatar'::text) AND (( SELECT (auth.uid())::text AS uid) = (storage.foldername(name))[1])));



  create policy "Give users access to own folder 1bs1gex_2"
  on "storage"."objects"
  as permissive
  for update
  to public
using (((bucket_id = 'avatar'::text) AND (( SELECT (auth.uid())::text AS uid) = (storage.foldername(name))[1])));



  create policy "Give users access to own folder 1bs1gex_3"
  on "storage"."objects"
  as permissive
  for insert
  to public
with check (((bucket_id = 'avatar'::text) AND (( SELECT (auth.uid())::text AS uid) = (storage.foldername(name))[1])));



